PythonWeb/PythonWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    # Tạo đường dẫn liên kết với các app
    path('', include('sanpham.urls')),
    path('user/', include('user.urls')),
    path('gio-hang/', include('giohang.urls')),
    path('tim-kiem/', include('timkiem.urls')),
    path('phongthuy/', include('phongthuy.urls')),
    url(r'^admin/', include('dbbackup_ui.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PythonWeb/contact/urls.py
from django.urls import path
from . import views

app_name = 'lienhe'
urlpatterns = [
    path('', views.home, name='contact'),
]

PythonWeb/giohang/urls.py
from django.urls import path
from . import views

app_name = 'giohang'
urlpatterns = [
    path('', views.cart_home, name='home'),
    path('cap-nhat/', views.cart_update, name='update'),
    path('xoa/', views.cart_delete, name='delete'),
    path('xoa-tat-ca/', views.cart_deleteall, name='deleteall'),
    #path('updatesl/', views.cart_updatesl, name='updatesl'),
    path('gio-hang-trong/', views.cart_empty, name='giohangtrong'),
    path('thanh-toan/', views.checkout_home, name='checkout'),
    path('thanh-cong/', views.thanhcong, name='thanhcong'),
]

PythonWeb/news/urls.py
from django.urls import path
from . import views

app_name = 'tintuc'
urlpatterns = [
    path('', views.home, name='news'),
    path("<int:id>/", views.tintuc, name='tintuc'),
]

PythonWeb/sanpham/urls.py
from django.urls import path

from . import views

app_name = 'sanpham'
urlpatterns = [
    path('', views.index, name='simso'),
    path("san-pham/<str:slug>", views.sanpham, name='sanpham'),
    path('sim-theo-gia/<str:slug>', views.simtheogia, name='simtheogia'),
    path('sim-theo-mang/<str:slug>', views.simtheomang, name='simtheomang'),
    path('sim-theo-loai/<str:slug>', views.simtheoloai, name='simtheoloai'),
    path('sim-nam-sinh/<str:slug>', views.simnamsinh, name='simnamsinh'),


]

PythonWeb/user/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from sanpham import models
import operator


app_name = 'user'
urlpatterns = [
    path("dang-ky/", views.dangky, name='dangky'),
    path("dang-nhap/", auth_views.LoginView.as_view(template_name='simso/page-user/dangnhap.html',
                                                    extra_context={
                                                        "stl": models.SimTheoLoai.objects.all(),
                                                        "sns": models.SimNamSinh.objects.all(),
                                                        "nm": models.NhaMang.objects.all(),
                                                        # "stg": sorted(models.SimTheoGia.objects.all(), key=operator.attrgetter('title')),
                                                    }),
         name='dangnhap'),
    path("dang-xuat/", auth_views.LogoutView.as_view(next_page='/'), name='dangxuat'),
    path("thong-tin-tai-khoan/", views.thongtintaikhoan, name='thongtintaikhoan'),
    path("doi-mat-khau/", views.doimatkhau, name='doimatkhau'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path("xac-thuc/", views.verify, name='xacthuc'),
    path("xac-thuc-sdt/", views.checkcode, name='xacthucsdt'),

]

PythonWeb/user/models.py
import datetime
from django.db import models
from django.contrib.auth.models import AbstractUser
from sanpham.models import SanPham


# Create your models here.
class CustomerUser(AbstractUser):
    SDT = models.CharField(default='', max_length=10, verbose_name='Số điện thoại')
    DiaChi = models.TextField(default='', verbose_name='Địa chỉ')
    choices = [('0', 'Nam'), ('1', 'Nữ'), ('2', 'Không xác định')]
    GioiTinh = models.CharField(choices=choices, default='2', max_length=20, verbose_name='Giới tính')
    NgaySinh = models.DateField(null=True, verbose_name='Ngày sinh')

    def HoTen(self):
        return self.first_name + " " + self.last_name

    class Meta:
        verbose_name_plural = 'Người dùng'


class BinhLuanDanhGia(models.Model):
    MaKH = models.ForeignKey(CustomerUser, on_delete=models.CASCADE)
    MaSP = models.ForeignKey(SanPham, on_delete=models.CASCADE)
    NgayBL = models.DateTimeField(auto_now_add=True)
    NoiDung = models.TextField(default='')
    SoSao = models.IntegerField(default=0)

PythonWeb/user/forms.py
from django import forms
import re
from .models import CustomerUser
from django.core.exceptions import ObjectDoesNotExist


class DangKyForm(forms.Form):

    username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tài khoản','label':'Tài khoản'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Mật khẩu'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Nhập lại mật khẩu'}))
    firstname = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Họ'}))
    lastname = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Tên'}))
    choices = [('0', 'Nam'), ('1', 'Nữ'), ('2', 'Không xác định')]
    gioitinh = forms.ChoiceField(choices=choices, widget=forms.RadioSelect(attrs={'class': 'ul-none'}))
    ngaysinh = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Ngày sinh', 'type': 'date'}))
    sdt = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Số điện thoại'}))
    diachi = forms.CharField(max_length=400, widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Địa chỉ'}))

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2 and password1:
                return password2
            raise forms.ValidationError("Mật khẩu không đúng")

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError("Tên tài khoản có chứa ký tự đặc biệt")
        try:
            CustomerUser.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError("Tài khoản đã tồn tại")

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            CustomerUser.objects.get(email=email)
        except ObjectDoesNotExist:
            return email
        raise forms.ValidationError("Email đã tồn tại")

    def clean_sdt(self):
        sdt = self.cleaned_data['sdt']
        try:
            CustomerUser.objects.get(SDT=sdt)
        except ObjectDoesNotExist:
            return sdt
        raise forms.ValidationError("Số điện thoại đã tồn tại")

    def save(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password2']
        email = self.cleaned_data['email']
        firstname = self.cleaned_data['firstname']
        lastname = self.cleaned_data['lastname']
        gioitinh = self.cleaned_data['gioitinh']
        ngaysinh = self.cleaned_data['ngaysinh']
        sdt = self.cleaned_data['sdt']
        diachi = self.cleaned_data['diachi']

        CustomerUser.objects.create_user(username=username,
                                         password=password,
                                         email=email,
                                         first_name=firstname,
                                         last_name=lastname,
                                         GioiTinh=gioitinh,
                                         NgaySinh=ngaysinh,
                                         SDT=sdt,
                                         DiaChi=diachi,
                                         is_active=False)

    def getiduser(self):
        return CustomerUser.objects.get(username=self.cleaned_data['username'])

class ThongTinForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    firstname = forms.CharField(max_length=200, widget=forms.TextInput(attrs={'class': 'form-control'}))
    lastname = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    choices = [('0', 'Nam'), ('1', 'Nữ'), ('2', 'Không xác định')]
    gioitinh = forms.ChoiceField(choices=choices, widget=forms.RadioSelect(attrs={'class': 'form-check-input ul-none'}))
    ngaysinh = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}))
    sdt = forms.CharField(max_length=10, widget=forms.TextInput(attrs={'class': 'form-control'}))
    diachi = forms.CharField(max_length=1000, widget=forms.Textarea(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ThongTinForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data['email']
        if not CustomerUser.objects.filter(email=email).exclude(id=self.user.id):
            return email
        raise forms.ValidationError("Email đã tồn tại")

    def clean_sdt(self):
        sdt = self.cleaned_data['sdt']
        if not CustomerUser.objects.filter(SDT=sdt).exclude(id=self.user.id):
            return sdt
        raise forms.ValidationError("Số điện thoại đã tồn tại")


class DoiMatKhauForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Mật khẩu'}))
    newpassword = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Mật khẩu mới'}))
    renewpassword = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Nhập lại mật khẩu mới'}))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(DoiMatKhauForm, self).__init__(*args, **kwargs)

    def clean_password(self):
        password = self.cleaned_data['password']
        if self.user.check_password(password):
            print(password)
            print(self.user.password)
            return password
        raise forms.ValidationError("Mật khẩu không đúng")

    def clean_renewpassword(self):
        if 'newpassword' in self.cleaned_data:
            newpassword = self.cleaned_data['newpassword']
            renewpassword = self.cleaned_data['renewpassword']
            if newpassword == renewpassword and newpassword:
                return renewpassword
            raise forms.ValidationError("Mật khẩu mới không đúng")

PythonWeb/user/templates/pages/baselogin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'home/img/icon/icon.png' %}" type="image/x-icon" />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}{% endblock %}</title>

    {% block cssblock %}
    {% endblock %}
</head>
<body>
        <!--================Menu Area =================-->
        {% include 'pages/navbar.html' %}
        <!--================End Menu Area =================-->
        <!--================Main Content Area =================-->
        {% block content %}{% endblock %}
        <!--================End Main Content Area =================-->
        <!--================Footer Area =================-->
        {% include 'pages/footer.html' %}
        <!--================End Footer Area =================-->
</body>

PythonWeb/user/templates/pages/danhmuc.html
{% if LoaiSanPhams %}
    {% for loaisanpham in LoaiSanPhams %}
            <li class="nav-item">
                <a alt="{{loaisanpham.TenLSP}}" href="{% url 'sanphamtheoloai' loaisanpham.id %}"  class="nav-link">
                    {{loaisanpham.TenLSP}}
                </a>
            </li>
    {% endfor %}
{% else %}
    Null
{% endif %}

PythonWeb/user/templates/pages/navbar.html
{% load static %}

<style>
    .cart_cart a:before {
        content: "{{ request.session.cart_items }}";
    }
</style>

<header class="shop_header_area carousel_menu_area">
    <div class="carousel_top_header black_top_header row m0">
        <div class="container">
            <div class="carousel_top_h_inner">
                <div class="float-md-right">
                    <ul class="account_list">
                        {% include 'pages/topmenu.html' %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="carousel_menu_inner">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="/"><img src="{% static 'home/img/logo.png' %}" alt="" style="width:250px"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown submenu active">
                            <a class="nav-link dropdown-toggle" href="{% url 'sanpham:home' %}" role="button"  aria-haspopup="true" aria-expanded="false">
                                Trang chủ
                            </a>
                        </li>
                        <li class="nav-item dropdown submenu">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Danh mục <i class="fa fa-angle-down" aria-hidden="true"></i>
                            </a>
                            <ul class="dropdown-menu">
                                {% include 'pages/danhmuc.html' %}
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'tintuc:news' %}">Tin tức</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'lienhe:contact' %}">Liên hệ</a></li>
                    </ul>
                    <ul class="navbar-nav justify-content-end">
                        <!--<li class="search_icon"><a href="#"><i class="icon-magnifier icons"></i></a></li>-->
                        <li class="user_icon"><a href="{% url 'user:thongtintaikhoan'%}"><i class="icon-user icons"></i></a></li>
                        <li class="cart_cart"><a href="{% url 'giohang:home' %}"><i class="icon-handbag icons"></i></a></li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</header>

PythonWeb/user/templates/pages/thongtintaikhoan.html
{% extends "pages/baselogin.html" %}
{% load static %}

{% block title %}
Thông tin tài khoản
{% endblock %}

{% block cssblock %}
    <!-- Icon css link -->
    <link href="{% static 'home/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/line-icon/css/simple-line-icons.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/elegant-icon/style.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Rev slider css -->
    <link href="{% static 'home/vendors/revolution/css/settings.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/revolution/css/layers.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/revolution/css/navigation.css' %}" rel="stylesheet">

    <!-- Extra plugin css -->
    <link href="{% static 'home/vendors/owl-carousel/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/bootstrap-selector/css/bootstrap-select.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/vertical-slider/css/jQuery.verticalCarousel.css' %}" rel="stylesheet">

    <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/PagedList.css' %}" rel="stylesheet" />


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        #id_firstname {
            width: 300px;
            float: left;
        }
        #id_lastname {
            width: 168px;
            float: left;
            margin-left:2px;
        }
        #id_gioitinh {
            float: left;
            margin-top:12.2px;
        }
        #id_gioitinh li {
            float: left;
            margin-left:20px;
        }
        #id_diachi {
            height:100px;
        }
        .errorlist li {
            color: red;
        }
    </style>
{% endblock %}

{% block content %}
    <h2 style="text-align:center;">Thông tin tài khoản</h2>
    <form class="form-horizontal" method="post" action="">
        {% csrf_token %}
        <hr />
        <div class="form-group" style="width: 500px; margin:auto; margin-top:20px;">
            <span class="control-label col-md-2">Họ</span>
            <span class="control-label col-md-2" style="float:right;margin-right:115px;">Tên</span>
            <div class="col-md-12">
                {{form.firstname}}
                {{ form.errors.firstname}}
                {{form.lastname}}
                {{ form.errors.lastname}}
            </div>
        </div>
        <div class="form-group" style="width: 500px; margin:auto; margin-top:50px;">
            <span class="control-label col-md-2">Email</span>
            <div class="col-md-12">
                {{form.email}}
                {{ form.errors.email}}
            </div>
        </div>
        <div class="form-group" style="width: 500px; margin:auto; margin-top:20px;">
            <span class="control-label col-md-2">Số điện thoại</span>
            <div class="col-md-12">
                {{form.sdt}}
                {{ form.errors.sdt}}
            </div>
        </div>
        <div class="form-group" style="width: 500px; margin:auto; margin-top:20px;">
            <span class="control-label col-md-2">Địa chỉ</span>
            <div class="col-md-12">
                {{form.diachi}}
                {{ form.errors.diachi}}
            </div>
        </div>
        <div class="form-group" style="width: 500px; margin:auto; margin-top:20px;">
            <span class="control-label col-md-2">Giới tính</span>
            <div class="col-md-12">
                {{form.gioitinh}}
                {% if user.GioiTinh == 0 %} checked='checked' {% endif %}
                {{ form.errors.gioitinh}}
            </div>
        </div>
        <div class="form-group" style="width: 500px; margin:auto; margin-top:50px;">
            <span class="control-label col-md-2">Ngày sinh</span>
            <div class="col-md-12">
                {{form.ngaysinh}}
                {{ form.errors.ngaysinh}}
            </div>
        </div>
        <div class="form-group" style="width: 500px; margin:auto; margin-top:20px;">
            <div class="col-md-offset-2 col-md-12">
                <input type="submit" value="Cập nhật" class="btn subs_btn btn-default" style="margin-left:50px; "/>
                <a href="{% url 'user:doimatkhau'%}" role="button" class="btn subs_btn btn-default" style="margin-left:40px; ">Đổi mật khẩu</a>
            </div>
        </div>
    </form>
{% endblock  %}

{% block jsblock %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'home/js/jquery-3.2.1.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'home/js/popper.min.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <!-- Rev slider js -->
    <script src="{% static 'home/vendors/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.video.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <!-- Extra plugin css -->
    <script src="{% static 'home/vendors/counterup/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'home/vendors/counterup/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'home/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'home/vendors/bootstrap-selector/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'home/vendors/image-dropdown/jquery.dd.min.js' %}"></script>
    <script src="{% static 'home/js/smoothscroll.js' %}"></script>
    <script src="{% static 'home/vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'home/vendors/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'home/vendors/magnify-popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'home/vendors/vertical-slider/js/jQuery.verticalCarousel.js' %}"></script>
    <script src="{% static 'home/vendors/jquery-ui/jquery-ui.js' %}"></script>
    <script src="{% static 'home/js/theme.js' %}"></script>
{% endblock %}

PythonWeb/user/templates/pages/topmenu.html
{% if user.username %}
    <li style="color: white;">Xin chào {{user.username}}</li>
    <li><a href="{% url 'user:dangxuat' %}">Đăng xuất</a></li>
{% else %}
    <li><a href="{% url 'user:dangky' %}">Đăng ký</a></li>
    <li><a href="{% url 'user:dangnhap' %}">Đăng nhập</a></li>
{% endif %}

PythonWeb/user/templates/pages/verify.html
{% extends "pages/baselogin.html" %}
{% load static %}

{% block title %}
Xác thực tài khoản
{% endblock %}

{% block cssblock %}
    <!-- Icon css link -->
    <link href="{% static 'home/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/line-icon/css/simple-line-icons.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/elegant-icon/style.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Rev slider css -->
    <link href="{% static 'home/vendors/revolution/css/settings.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/revolution/css/layers.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/revolution/css/navigation.css' %}" rel="stylesheet">

    <!-- Extra plugin css -->
    <link href="{% static 'home/vendors/owl-carousel/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/bootstrap-selector/css/bootstrap-select.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/vertical-slider/css/jQuery.verticalCarousel.css' %}" rel="stylesheet">

    <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/PagedList.css' %}" rel="stylesheet" />


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{% endblock %}

{% block content %}
<div class="track_inner">
    <div class="track_title" style="padding-bottom:30px;">
        <h2>Xác thực tài khoản</h2>
        <p>Vui lòng chọn một trong hai phương thức dưới đây để xác thực tài khoản.</p>
    </div>
    <form class="track_form row" method="POST" action=".">
        {% csrf_token %}
        <div class="col-lg-12 " style="text-align: center; font-size: 18px;">
            <input type="radio" name="verify" value="sdt" id="id_sdt" checked>
            <label for="id_sdt">Xác thực bằng số điện thoại.</label>
        </div>
        <div class="col-lg-12 " style="text-align: center; font-size: 18px;">
            <input type="radio" name="verify" value="email" id="id_email">
            <label for="id_email">Xác thực bằng email.</label>
        </div>
        <div class="col-lg-12 form-group">
            <button type="submit" value="submit" class="btn subs_btn form-control">Xác thực</button>
        </div>
    </form>
</div>

{% endblock  %}

{% block jsblock %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'home/js/jquery-3.2.1.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'home/js/popper.min.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <!-- Rev slider js -->
    <script src="{% static 'home/vendors/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.video.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <!-- Extra plugin css -->
    <script src="{% static 'home/vendors/counterup/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'home/vendors/counterup/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'home/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'home/vendors/bootstrap-selector/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'home/vendors/image-dropdown/jquery.dd.min.js' %}"></script>
    <script src="{% static 'home/js/smoothscroll.js' %}"></script>
    <script src="{% static 'home/vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'home/vendors/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'home/vendors/magnify-popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'home/vendors/vertical-slider/js/jQuery.verticalCarousel.js' %}"></script>
    <script src="{% static 'home/vendors/jquery-ui/jquery-ui.js' %}"></script>
    <script src="{% static 'home/js/theme.js' %}"></script>
{% endblock %}