PythonWeb/PythonWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    # Tạo đường dẫn liên kết với các app
    path('', include('sanpham.urls')),
    path('user/', include('user.urls')),
    path('gio-hang/', include('giohang.urls')),
    path('tim-kiem/', include('timkiem.urls')),
    path('phongthuy/', include('phongthuy.urls')),
    url(r'^admin/', include('dbbackup_ui.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PythonWeb/contact/urls.py
from django.urls import path
from . import views

app_name = 'lienhe'
urlpatterns = [
    path('', views.home, name='contact'),
]

PythonWeb/giohang/urls.py
from django.urls import path
from . import views

app_name = 'giohang'
urlpatterns = [
    path('', views.cart_home, name='home'),
    path('cap-nhat/', views.cart_update, name='update'),
    path('xoa/', views.cart_delete, name='delete'),
    path('xoa-tat-ca/', views.cart_deleteall, name='deleteall'),
    #path('updatesl/', views.cart_updatesl, name='updatesl'),
    path('gio-hang-trong/', views.cart_empty, name='giohangtrong'),
    path('thanh-toan/', views.checkout_home, name='checkout'),
    path('thanh-cong/', views.thanhcong, name='thanhcong'),
]

PythonWeb/news/urls.py
from django.urls import path
from . import views

app_name = 'tintuc'
urlpatterns = [
    path('', views.home, name='news'),
    path("<int:id>/", views.tintuc, name='tintuc'),
]

PythonWeb/sanpham/urls.py
from django.urls import path

from . import views

app_name = 'sanpham'
urlpatterns = [
    path('', views.index, name='simso'),
    path("san-pham/<str:slug>", views.sanpham, name='sanpham'),
    path('sim-theo-gia/<str:slug>', views.simtheogia, name='simtheogia'),
    path('sim-theo-mang/<str:slug>', views.simtheomang, name='simtheomang'),
    path('sim-theo-loai/<str:slug>', views.simtheoloai, name='simtheoloai'),
    path('sim-nam-sinh/<str:slug>', views.simnamsinh, name='simnamsinh'),


]

PythonWeb/user/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from sanpham import models
import operator


app_name = 'user'
urlpatterns = [
    path("dang-ky/", views.dangky, name='dangky'),
    path("dang-nhap/", auth_views.LoginView.as_view(template_name='simso/page-user/dangnhap.html',
                                                    extra_context={
                                                        "stl": models.SimTheoLoai.objects.all(),
                                                        "sns": models.SimNamSinh.objects.all(),
                                                        "nm": models.NhaMang.objects.all(),
                                                        # "stg": sorted(models.SimTheoGia.objects.all(), key=operator.attrgetter('title')),
                                                    }),
         name='dangnhap'),
    path("dang-xuat/", auth_views.LogoutView.as_view(next_page='/'), name='dangxuat'),
    path("thong-tin-tai-khoan/", views.thongtintaikhoan, name='thongtintaikhoan'),
    path("doi-mat-khau/", views.doimatkhau, name='doimatkhau'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path("xac-thuc/", views.verify, name='xacthuc'),
    path("xac-thuc-sdt/", views.checkcode, name='xacthucsdt'),

]

PythonWeb/news/models.py
from django.db import models


# Create your models here.
# Tạo bảng tin tức
class TinTuc(models.Model):
    Title = models.TextField(null=True)
    Short_Body = models.TextField(null=True)
    Body = models.TextField()
    CoverImage = models.ImageField(default='product-default.jpg')
    Date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Title

PythonWeb/news/views.py
from django.shortcuts import render
from .models import TinTuc
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
def home(request):
    # Lấy dữ liệu từ database
    tintuc = TinTuc.objects.get_queryset().order_by('-id')

    # Phân trang
    page = request.GET.get('page', 1)
    paginator = Paginator(tintuc, 6)
    try:
        TinTucs = paginator.page(page)
    except PageNotAnInteger:
        TinTucs = paginator.page(1)
    except EmptyPage:
        TinTucs = paginator.page(paginator.num_pages)

    Data = {"TinTucs": TinTucs,
            }
    return render(request, 'simso/news.html', Data)

def tintuc(request, id):
    # Lấy dữ liệu từ database
    tintuc = TinTuc.objects.get(id=id)

    Data = {'TinTuc': tintuc,
            "TinTucKhacs": TinTuc.objects.all().order_by('-id').exclude(id=id)[:10],
            }
    return render(request, 'simso/tintuc.html', Data)

PythonWeb/news/templates/pages/basenews.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'home/img/icon/icon.png' %}" type="image/x-icon" />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}{% endblock %}</title>

    {% block cssblock %}
    {% endblock %}
</head>
<body>
        <!--================Menu Area =================-->
        {% include 'pages/navbar.html' %}
        <!--================End Menu Area =================-->
        <!--================Main Content Area =================-->
        {% block content %}{% endblock %}
        <!--================End Main Content Area =================-->
        <!--================Footer Area =================-->
        {% include 'pages/footer.html' %}
        <!--================End Footer Area =================-->
</body>

PythonWeb/news/templates/pages/danhmuc.html
{% if LoaiSanPhams %}
    {% for loaisanpham in LoaiSanPhams %}
            <li class="nav-item">
                <a alt="{{loaisanpham.TenLSP}}" href="{% url 'sanphamtheoloai' loaisanpham.id %}"  class="nav-link">
                    {{loaisanpham.TenLSP}}
                </a>
            </li>
    {% endfor %}
{% else %}
    Null
{% endif %}

PythonWeb/news/templates/pages/footer.html
{% load static %}
<section class="world_service">
    <div class="container">
        <div class="world_service_inner">
            <div class="row">
                <div class="col-lg-3">
                    <div class="world_service_item">
                        <h4><img src="{% static 'home/img/icon/world-icon-1.png' %}" alt="">Dịch vụ toàn quốc</h4>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="world_service_item">
                        <h4><img src="{% static 'home/img/icon/world-icon-2.png' %}" alt="">Hỗ trợ 24/7</h4>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="world_service_item">
                        <h4><img src="{% static 'home/img/icon/world-icon-3.png' %}" alt="">Uy tín, an toàn</h4>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="world_service_item">
                        <h4><img src="{% static 'home/img/icon/world-icon-4.png' %}" alt="">Giao hàng nhanh</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<footer class="footer_area border_none">
            <div class="container">
                <div class="footer_widgets">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-6">
                            <aside class="f_widget f_about_widget">
                                <img src="{% static 'home/img/logo.png' %}" alt="">
                                <p>Cichlid Shop là trang web tự làm của 1 nhóm sinh viên</p>
                                <h6>Mạng xã hội:</h6>
                                <ul>
                                    <li><a href="#"><i class="social_facebook"></i></a></li>
                                    <li><a href="#"><i class="social_twitter"></i></a></li>
                                    <li><a href="#"><i class="social_pinterest"></i></a></li>
                                    <li><a href="#"><i class="social_instagram"></i></a></li>
                                    <li><a href="#"><i class="social_youtube"></i></a></li>
                                </ul>
                            </aside>
                        </div>
                        <div class="col-lg-3 col-md-4 col-6">
                            <aside class="f_widget link_widget f_info_widget">
                                <div class="f_w_title">
                                    <h3>Thông tin</h3>
                                </div>
                                <ul>
                                    <li><a href="#">Giới thiệu</a></li>
                                    <li><a href="#">Thông tin vận chuyển</a></li>
                                    <li><a href="#">Điều khoản và điều kiện</a></li>
                                    <li><a href="#">Trung tâm hỗ trợ</a></li>
                                    <li><a href="#">Trả lại và hoàn tiền</a></li>
                                </ul>
                            </aside>
                        </div>
                        <div class="col-lg-3 col-md-4 col-6">
                            <aside class="f_widget link_widget f_service_widget">
                                <div class="f_w_title">
                                    <h3>Dịch vụ khách hàng</h3>
                                </div>
                                <ul>
                                    <li><a href="#">Tài khoản</a></li>
                                    <li><a href="#">Lịch sử giao dịch</a></li>
                                    <li><a href="#">Giỏ hàng</a></li>
                                    <li><a href="#">Tin tức mới</a></li>
                                    <li><a href="#">Liên hệ</a></li>
                                </ul>
                            </aside>
                        </div>
                        <div class="col-lg-2 col-md-4 col-6">
                            <aside class="f_widget link_widget f_extra_widget">
                                <div class="f_w_title">
                                    <h3>Ngoài ra</h3>
                                </div>
                                <ul>
                                    <li><a href="#">Thương hiệu</a></li>
                                    <li><a href="#">Phiếu quà tặng</a></li>
                                    <li><a href="#">Chi nhánh</a></li>
                                    <li><a href="#">Đặc biệt</a></li>
                                </ul>
                            </aside>
                        </div>

                    </div>
                </div>
                <div class="footer_copyright">
                    <h5>
                        ©
                        <script>document.write(new Date().getFullYear());</script> <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </h5>
                </div>
            </div>
        </footer>

PythonWeb/news/templates/pages/navbar.html
{% load static %}

<style>
    .cart_cart a:before {
        content: "{{ request.session.cart_items }}";
    }
</style>

<header class="shop_header_area carousel_menu_area">
    <div class="carousel_top_header black_top_header row m0">
        <div class="container">
            <div class="carousel_top_h_inner">
                <div class="float-md-right">
                    <ul class="account_list">
                        {% include 'pages/topmenu.html' %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="carousel_menu_inner">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="/"><img src="{% static 'home/img/logo.png' %}" alt="" style="width:250px"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown submenu active">
                            <a class="nav-link dropdown-toggle" href="{% url 'sanpham:home' %}" role="button"  aria-haspopup="true" aria-expanded="false">
                                Trang chủ
                            </a>
                        </li>
                        <li class="nav-item dropdown submenu">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Danh mục <i class="fa fa-angle-down" aria-hidden="true"></i>
                            </a>
                            <ul class="dropdown-menu">
                                {% include 'pages/danhmuc.html' %}
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'tintuc:news' %}">Tin tức</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'lienhe:contact' %}">Liên hệ</a></li>
                    </ul>
                    <ul class="navbar-nav justify-content-end">
                        <!--<li class="search_icon"><a href="#"><i class="icon-magnifier icons"></i></a></li>-->
                        <li class="user_icon"><a href="{% url 'user:thongtintaikhoan'%}"><i class="icon-user icons"></i></a></li>
                        <li class="cart_cart"><a href="{% url 'giohang:home' %}"><i class="icon-handbag icons"></i></a></li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</header>

PythonWeb/news/templates/pages/news.html
{% extends "pages/basenews.html" %}
{% load static %}

{% block title %}
Tin tức
{% endblock %}

{% block cssblock %}
    <!-- Icon css link -->
    <link href="{% static 'home/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/line-icon/css/simple-line-icons.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/elegant-icon/style.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Rev slider css -->
    <link href="{% static 'home/vendors/revolution/css/settings.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/revolution/css/layers.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/revolution/css/navigation.css' %}" rel="stylesheet">

    <!-- Extra plugin css -->
    <link href="{% static 'home/vendors/owl-carousel/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/bootstrap-selector/css/bootstrap-select.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/vertical-slider/css/jQuery.verticalCarousel.css' %}" rel="stylesheet">

    <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/PagedList.css' %}" rel="stylesheet" />


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{% endblock %}

{% block content %}
    <div class="container">
        <form class="col-lg-4 float-md-right" method="get" action="{% url 'timkiem:ketquatimkiemtintuc' %}">
            <input type="text" name="q" class="form-control float-md-left" placeholder="Tìm kiếm" aria-label="Search" style="width:88%;" value="{{request.GET.q}}">
            <span class="float-md-right">
                <button class="btn btn-danger" type="submit"><i class="icon-magnifier icons"></i></button>
            </span>
        </form>
    </div>
    <section class="categories_product_main p_80">
        <div class="container">

            <div class="categories_main_inner">
                <div class="row row_disable">
                    <div class="col-lg-12 float-md-right">
                        <div class="categories_product_area">
                            <div class="row">
                                {% for tintuc in TinTucs %}
                                    <div class="col-lg-12 col-sm-6">
                                        <a href="{% url 'tintuc:tintuc' tintuc.id %}" style="color: black;">
                                            <div class="l_product_item" style="margin: 10px 0px; border: none;">
                                                <div class="col-lg-3 col-sm-6 float-md-left">
                                                    <div class="l_p_img" style="height:265px;width:100%;">
                                                        <img src="{{tintuc.CoverImage.url}}" alt="{{tintuc.Title}}" style="height:100%;">
                                                    </div>
                                                </div>
                                                <div class="col-lg-9 col-sm-6 float-md-right">
                                                    <div class="l_p_info">
                                                       <h2>{{tintuc.Title}}</h2>
                                                        <span>{{tintuc.Date}}</span>
                                                        <br />
                                                        <div style="height:50%;">
                                                            {{tintuc.Short_Body}}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <hr  style="width: 100%"/>
                                {% endfor %}
                            </div>

                            <!--Phân trang-->
                            <div style="text-align:center;">
                                {% if TinTucs.has_other_pages %}
                                    <ul class="pagination">
                                        {% if TinTucs.has_previous %}
                                            <li><a href="?page={{ TinTucs.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                            <li class="disabled"><span>&laquo;</span></li>
                                        {% endif %}
                                        {% for i in TinTucs.paginator.page_range %}
                                            {% if TinTucs.number == i %}
                                                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if TinTucs.has_next %}
                                            <li><a href="?page={{ TinTucs.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                            <li class="disabled"><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock  %}

{% block jsblock %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'home/js/jquery-3.2.1.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'home/js/popper.min.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <!-- Rev slider js -->
    <script src="{% static 'home/vendors/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.video.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <!-- Extra plugin css -->
    <script src="{% static 'home/vendors/counterup/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'home/vendors/counterup/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'home/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'home/vendors/bootstrap-selector/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'home/vendors/image-dropdown/jquery.dd.min.js' %}"></script>
    <script src="{% static 'home/js/smoothscroll.js' %}"></script>
    <script src="{% static 'home/vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'home/vendors/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'home/vendors/magnify-popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'home/vendors/vertical-slider/js/jQuery.verticalCarousel.js' %}"></script>
    <script src="{% static 'home/vendors/jquery-ui/jquery-ui.js' %}"></script>
    <script src="{% static 'home/js/theme.js' %}"></script>
{% endblock %}

PythonWeb/news/templates/pages/tintuc.html
{% extends "pages/basenews.html" %}
{% load static %}

{% block title %}
{{TinTuc.Title}}
{% endblock %}

{% block cssblock %}
    <!-- Icon css link -->
    <link href="{% static 'home/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/line-icon/css/simple-line-icons.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/elegant-icon/style.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Rev slider css -->
    <link href="{% static 'home/vendors/revolution/css/settings.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/revolution/css/layers.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/revolution/css/navigation.css' %}" rel="stylesheet">

    <!-- Extra plugin css -->
    <link href="{% static 'home/vendors/owl-carousel/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/bootstrap-selector/css/bootstrap-select.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/vertical-slider/css/jQuery.verticalCarousel.css' %}" rel="stylesheet">

    <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/PagedList.css' %}" rel="stylesheet" />


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{% endblock %}

{% block content %}
    <section class="categories_product_main p_80">
        <div class="container">
            <div class="categories_main_inner">
                <div class="row row_disable">
                    <div class="col-lg-9 float-md-right">
                        <div class="categories_product_area">
                            <div class="row">
                                <div class="col-lg-12 col-sm-6">
                                    <div class="l_product_item" style="margin: 10px 0px; border: none;">
                                        <div class="l_p_info">
                                           <h2>{{TinTuc.Title}}</h2>
                                            <span>{{TinTuc.Date}}</span>
                                            <h4 style="margin: 20px 0px;">{{TinTuc.Short_Body}}</h4>
                                            <span>{{TinTuc.Body|safe|linebreaks}}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 float-md-right">
                        <div class="categories_sidebar">
                            <aside class="l_widgest l_p_categories_widget">
                                <div class="l_w_title">
                                    <h3>Tin tức khác</h3>
                                </div>
                                <ul class="navbar-nav">
                                    {% for tintuckhac in TinTucKhacs %}
                                        <li class="nav-item">
                                            <a class="nav-link" href="{% url 'tintuc:tintuc' tintuckhac.id %}">
                                                {{tintuckhac.Title}}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </aside>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock  %}

{% block jsblock %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'home/js/jquery-3.2.1.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'home/js/popper.min.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <!-- Rev slider js -->
    <script src="{% static 'home/vendors/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.video.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <!-- Extra plugin css -->
    <script src="{% static 'home/vendors/counterup/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'home/vendors/counterup/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'home/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'home/vendors/bootstrap-selector/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'home/vendors/image-dropdown/jquery.dd.min.js' %}"></script>
    <script src="{% static 'home/js/smoothscroll.js' %}"></script>
    <script src="{% static 'home/vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'home/vendors/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'home/vendors/magnify-popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'home/vendors/vertical-slider/js/jQuery.verticalCarousel.js' %}"></script>
    <script src="{% static 'home/vendors/jquery-ui/jquery-ui.js' %}"></script>
    <script src="{% static 'home/js/theme.js' %}"></script>
{% endblock %}

PythonWeb/news/templates/pages/topmenu.html
{% if user.username %}
    <li style="color: white;">Xin chào {{user.username}}</li>
    <li><a href="{% url 'user:dangxuat' %}">Đăng xuất</a></li>
{% else %}
    <li><a href="{% url 'user:dangky' %}">Đăng ký</a></li>
    <li><a href="{% url 'user:dangnhap' %}">Đăng nhập</a></li>
{% endif %}