PythonWeb/PythonWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    # Tạo đường dẫn liên kết với các app
    path('', include('sanpham.urls')),
    path('user/', include('user.urls')),
    path('gio-hang/', include('giohang.urls')),
    path('tim-kiem/', include('timkiem.urls')),
    path('phongthuy/', include('phongthuy.urls')),
    url(r'^admin/', include('dbbackup_ui.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PythonWeb/giohang/urls.py
from django.urls import path
from . import views

app_name = 'giohang'
urlpatterns = [
    path('', views.cart_home, name='home'),
    path('cap-nhat/', views.cart_update, name='update'),
    path('xoa/', views.cart_delete, name='delete'),
    path('xoa-tat-ca/', views.cart_deleteall, name='deleteall'),
    #path('updatesl/', views.cart_updatesl, name='updatesl'),
    path('gio-hang-trong/', views.cart_empty, name='giohangtrong'),
    path('thanh-toan/', views.checkout_home, name='checkout'),
    path('thanh-cong/', views.thanhcong, name='thanhcong'),
]

PythonWeb/news/urls.py
from django.urls import path
from . import views

app_name = 'tintuc'
urlpatterns = [
    path('', views.home, name='news'),
    path("<int:id>/", views.tintuc, name='tintuc'),
]

PythonWeb/sanpham/urls.py
from django.urls import path

from . import views

app_name = 'sanpham'
urlpatterns = [
    path('', views.index, name='simso'),
    path("san-pham/<str:slug>", views.sanpham, name='sanpham'),
    path('sim-theo-gia/<str:slug>', views.simtheogia, name='simtheogia'),
    path('sim-theo-mang/<str:slug>', views.simtheomang, name='simtheomang'),
    path('sim-theo-loai/<str:slug>', views.simtheoloai, name='simtheoloai'),
    path('sim-nam-sinh/<str:slug>', views.simnamsinh, name='simnamsinh'),


]

PythonWeb/user/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from sanpham import models
import operator


app_name = 'user'
urlpatterns = [
    path("dang-ky/", views.dangky, name='dangky'),
    path("dang-nhap/", auth_views.LoginView.as_view(template_name='simso/page-user/dangnhap.html',
                                                    extra_context={
                                                        "stl": models.SimTheoLoai.objects.all(),
                                                        "sns": models.SimNamSinh.objects.all(),
                                                        "nm": models.NhaMang.objects.all(),
                                                        # "stg": sorted(models.SimTheoGia.objects.all(), key=operator.attrgetter('title')),
                                                    }),
         name='dangnhap'),
    path("dang-xuat/", auth_views.LogoutView.as_view(next_page='/'), name='dangxuat'),
    path("thong-tin-tai-khoan/", views.thongtintaikhoan, name='thongtintaikhoan'),
    path("doi-mat-khau/", views.doimatkhau, name='doimatkhau'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path("xac-thuc/", views.verify, name='xacthuc'),
    path("xac-thuc-sdt/", views.checkcode, name='xacthucsdt'),

]

PythonWeb/giohang/models.py
from django.db import models
from sanpham.models import SanPham
from user.models import CustomerUser
from django.db.models.signals import pre_save, post_save, m2m_changed
import urllib.request
import json


# Create your models here.
# class quản lí giỏ hàng
class GioHangManager(models.Manager):

    def new_or_get(self, request):
        # Lấy cart_id từ session
        cart_id = request.session.get("cart_id", None)
        # Tìm cart_id trong database
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            cart_obj = qs.first()
            CTGHMoi(cart_obj)
            new_obj = False
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = self.GioHangMoi(user=request.user)
            CTGHMoi(cart_obj)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    # Tạo giỏ hàng mới
    def GioHangMoi(self,user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


# Tạo chi tiết giỏ hàng mới
def CTGHMoi(cart_obj=None):
    sanphams = cart_obj.SanPhams.all()
    for item in sanphams:
        ctgh_obj, created = CTGH.objects.get_or_create(GH=cart_obj, SP=item)
        ctgh_obj.DonGia = item.Gia
        ctgh_obj.save()


# Tạo bảng giỏ hàng
class GioHang(models.Model):
    user = models.ForeignKey(CustomerUser, on_delete=models.CASCADE, null= True, blank= True, verbose_name='Người đặt')
    SanPhams = models.ManyToManyField(SanPham, blank=True, verbose_name='Danh sách sản phẩm')
    TongTien = models.FloatField(default=0, verbose_name='Tổng tiền')

    objects = GioHangManager()

    def __str__(self):
        return str(self.id)

    def get_sanphams(self):
        return " - ".join([s.SoSim for s in self.SanPhams.all()])

    get_sanphams.short_description = "Danh sách sản phẩm"

    class Meta:
        verbose_name_plural = 'Giỏ hàng'


# Tạo bảng chi tiết giỏ hàng
class CTGH(models.Model):
    GH = models.ForeignKey(GioHang, on_delete=models.CASCADE, null=True, verbose_name='Giỏ hàng')
    SP = models.ForeignKey(SanPham, on_delete=models.CASCADE, null=True, verbose_name='Sản phẩm')
    DonGia = models.IntegerField(default=0, verbose_name='Giá')

    def __str__(self):
        return str(self.id)

    def ToUSD(self):
        req = 'https://openexchangerates.org/api/latest.json?app_id=256d3b5746664d27bc090b385afd574d&symbols=VND'
        data = urllib.request.urlopen(req).read()
        data = json.loads(data.decode('utf-8'))
        rates = data["rates"]
        return self.DonGia / rates['VND']

    class Meta:
        verbose_name_plural = 'Chi tiết giỏ hàng'

#Cập nhật từ admin
def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        sanphams = instance.SanPhams.all()
        if sanphams is None:
            CTGH.objects.filter(GH=instance).delete()
        else:
            ctghs = CTGH.objects.filter(GH=instance)
            for item in ctghs:
                if item.SP not in sanphams:
                    CTGH.objects.get(GH=item.GH, SP=item.SP).delete()

        tongtien = 0
        CTGHMoi(instance)
        ListSP = CTGH.objects.filter(GH=instance)
        for item in ListSP:
            tongtien += item.DonGia
        instance.TongTien = tongtien
        instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=GioHang.SanPhams.through)

PythonWeb/giohang/views.py
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from .models import GioHang, CTGH, CTGHMoi
from sanpham.models import SanPham
from hoadon.models import HoaDon
from user.models import CustomerUser
from sanpham.models import SimNamSinh, SimTheoLoai, SimTheoGia, NhaMang
import operator


# Create your views here.
# Tạo trang giỏ hàng
def cart_home(request):
    cart_obj, new_obj = GioHang.objects.new_or_get(request)
    sanphams = cart_obj.SanPhams.all()

    tongtien = 0
    ListSP = CTGH.objects.filter(GH=cart_obj)
    if ListSP:
        for item in ListSP:
            tongtien += item.DonGia
    cart_obj.TongTien = tongtien
    cart_obj.save()

    ctgh_obj = CTGH.objects.filter(GH=cart_obj)

    # Lấy tổng số lượng sản phẩm
    soluongsp = 0
    if ctgh_obj is not None:
        for item in ctgh_obj:
            soluongsp += 1

    request.session['cart_items'] = soluongsp

    if not sanphams:
        return redirect('gio-hang-trong/')

    stl = SimTheoLoai.objects.all()
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()
    # Sắp xếp danh mục sim theo giá theo title
    stg_dsx = sorted(stg, key=operator.attrgetter('title'))


    Data = {
        "stl": stl,
        "sns": sns,
        "nm": nm,
        "stg": stg_dsx,
        "GioHangs": cart_obj,
        "CTGHs": ctgh_obj}
    return render(request, 'simso/page-cart/cart.html', Data)


#Cập nhật giỏ hàng
def cart_update(request):
    #Lấy id sản phẩm
    product_id = request.POST.get('product_id')
    current_url = request.POST.get('current_url')

    cart_obj, new_obj = GioHang.objects.new_or_get(request)

    if product_id is not None:
        try:
            obj = SanPham.objects.get(id=product_id)
        except:
            return redirect('giohang:home')

        #Kiểm tra sản phẩm trong giỏ hàng
        if obj in cart_obj.SanPhams.all():
            return redirect(current_url)
        else:
            cart_obj.SanPhams.add(obj)
            cart_obj.TongTien += obj.Gia
            cart_obj.save()

    #Lấy tổng số lượng sản phẩm
    sanphams = CTGH.objects.filter(GH=cart_obj)
    soluongsp = 0
    if sanphams is not None:
        for item in sanphams:
            soluongsp += 1

    request.session['cart_items'] = soluongsp

    if current_url:
        return redirect(current_url)
    else:
        return redirect('giohang:home')


#Xóa sản phẩm trong giỏ hàng
def cart_delete(request):
    #Lấy id sản phẩm
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            obj = SanPham.objects.get(id=product_id)
        except:
            return redirect('giohang:home')

        cart_obj, new_obj = GioHang.objects.new_or_get(request)

        #Kiểm tra sản phẩm trong giỏ hàng
        if obj in cart_obj.SanPhams.all():
            CTGH.objects.filter(GH=cart_obj, SP=obj).delete()
            cart_obj.SanPhams.remove(product_id)
            return redirect('giohang:update')

    return redirect('giohang:home')

#Xóa tất cả sản phẩm trong giỏ hàng
def cart_deleteall(request):
    cart_obj, new_obj = GioHang.objects.new_or_get(request)
    CTGH.objects.filter(GH=cart_obj).delete()
    cart_obj.SanPhams.remove(*cart_obj.SanPhams.all())
    request.session['cart_items'] = 0
    return redirect('giohang:home')


#Cập nhật số lượng của sản phẩm
# def cart_updatesl(request):
#     # Lấy id sản phẩm
#     product_id = request.POST.get('product_id')
#
#     #Lấy số lượng sản phẩm
#     soluong = (int)(request.POST.get('SoLuong'))
#     cart_obj, new_obj = GioHang.objects.new_or_get(request)
#
#     if soluong == 0:
#         CTGH.objects.filter(GH=cart_obj, SP=product_id).delete()
#         cart_obj.SanPhams.remove(product_id)
#     else:
#         item = CTGH.objects.get(GH=cart_obj, SP=product_id)
#         item.SoLuong = soluong
#         item.save()
#     return redirect('giohang:home')

#Giỏ hàng trống
def cart_empty(request):
    stl = SimTheoLoai.objects.all()
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()
    # Sắp xếp danh mục sim theo giá theo title
    stg_dsx = sorted(stg, key=operator.attrgetter('title'))
    Data = {
        "stl": stl,
        "sns": sns,
        "nm": nm,
        "stg": stg_dsx,
    }
    return render(request, 'simso/page-cart/giohangtrong.html', Data)

#Đặt hàng
def checkout_home(request):
    user = request.user
    if not user.is_authenticated:
        return redirect('/user/dang-nhap')

    cart_obj, cart_created = GioHang.objects.new_or_get(request)
    ctgh = CTGH.objects.filter(GH=cart_obj)
    order_obj = None

    error = ""
    if request.method == "POST":
        if cart_created:
            return redirect("giohang:home")
        else:
            order_obj, new_order_obj = HoaDon.objects.get_or_create(GH=cart_obj)

        is_done = order_obj.check_done()
        if is_done:
            return redirect("giohang:thanhcong")
        else:
            error = "Vui lòng kiểm tra thông tin đặt hàng"

    stl = SimTheoLoai.objects.all()
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()
    # Sắp xếp danh mục sim theo giá theo title
    stg_dsx = sorted(stg, key=operator.attrgetter('title'))

    Data = {
        "stl": stl,
        "sns": sns,
        "nm": nm,
        "stg": stg_dsx,
        "Order_obj": order_obj,
        "Cart_obj": cart_obj,
        "CTGHs": ctgh,
        "User": user,
        "Error": error,
        }
    return render(request, 'simso/page-cart/checkout.html', Data)

#Đặt hàng thành công
def thanhcong(request):
    user = request.user
    cart_obj, cart_created = GioHang.objects.new_or_get(request)
    ctgh = CTGH.objects.filter(GH=cart_obj)
    order_obj = None

    if cart_created:
        return redirect("giohang:home")
    else:
        order_obj, new_order_obj = HoaDon.objects.get_or_create(GH=cart_obj)

    #Gửi thông tin hóa đơn cho người dùng và admin
    mail_subject = '[Sim Đức Lộc] Thông tin hóa đơn.'
    message = render_to_string('simso/page-cart/thongtinhoadon.html', {
        'user': user,
        'Ctghs': ctgh,
        'Cart_obj': cart_obj,
        'Order_obj': order_obj,
    })
    to_email = user.email
    email = EmailMessage(
        mail_subject, message, to=[to_email]
    )
    email.content_subtype = 'html'
    email.mixed_subtype = 'related'
    email.send()


    mail_subject_admin = 'Bạn có một đơn đặt hàng mới.'
    message_admin = render_to_string('simso/page-cart/thongtinhoadonadmin.html', {
        'User': user,
        'Ctghs': ctgh,
        'Cart_obj': cart_obj,
        'Order_obj': order_obj,
    })
    to_email_admins = CustomerUser.objects.get(is_superuser=True).email
    email_admin = EmailMessage(
        mail_subject_admin, message_admin, to=[to_email_admins]
    )
    email_admin.content_subtype = 'html'
    email_admin.mixed_subtype = 'related'
    email_admin.send()

    request.session['cart_items'] = 0

    # Thay đổi trạng thái thanh toán của hóa đơn khi thanh toán bằng paypal
    if request.GET.get('st') and request.GET.get('st') == 'Completed':
        order_obj.ThanhToan = True
        order_obj.save()
    del request.session['cart_id']

    stl = SimTheoLoai.objects.all()
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()
    # Sắp xếp danh mục sim theo giá theo title
    stg_dsx = sorted(stg, key=operator.attrgetter('title'))
    Data = {
        "stl": stl,
        "sns": sns,
        "nm": nm,
        "stg": stg_dsx,
    }
    return render(request, 'simso/page-cart/thanhcong.html', Data)

PythonWeb/giohang/templates/pages/cart.html
{% extends "pages/basecart.html" %}
{% load static %}

{% block title %}
Giỏ hàng
{% endblock %}

{% block cssblock %}
    <!-- Icon css link -->
    <link href="{% static 'home/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/line-icon/css/simple-line-icons.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/elegant-icon/style.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Rev slider css -->
    <link href="{% static 'home/vendors/revolution/css/settings.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/revolution/css/layers.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/revolution/css/navigation.css' %}" rel="stylesheet">

    <!-- Extra plugin css -->
    <link href="{% static 'home/vendors/owl-carousel/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/bootstrap-selector/css/bootstrap-select.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendors/vertical-slider/css/jQuery.verticalCarousel.css' %}" rel="stylesheet">

    <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/PagedList.css' %}" rel="stylesheet" />


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{% endblock %}

{% block content %}

    <section class="shopping_cart_area p_100">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="cart_items">
                        <h3>Giỏ hàng của bạn</h3>
                        <div class="table-responsive-md">
                            <table class="table">
                                <tbody>
                                    {% for sanpham in GioHangs.SanPhams.all %}
                                        <tr>
                                            <th scope="row">
                                                {% include 'pages/xoakhoigiohang.html' %}
                                            </th>
                                            <td>
                                                <a href="{% url 'sanpham:sanpham' sanpham.id %}">
                                                    <div class="media">
                                                        <div class="d-flex">
                                                            <img src="{{sanpham.Anh.url}}" alt="{{sanpham.TenSanPham}}" style="width: 102px; height: 123px;" />
                                                        </div>
                                                        <div class="media-body">
                                                            <h4>{{sanpham.TenSanPham}}</h4>
                                                        </div>
                                                    </div>
                                                </a>
                                            </td>
                                            <td><p class="red">{{sanpham.GiaChinhThuc}} VNĐ</p></td>
                                            {% include 'pages/capnhatsoluong.html' %}
                                        </tr>
                                    {% endfor %}
                                    <tr>
                                        <th scope="row">
                                        </th>
                                    </tr>
                                    <tr class="last">
                                        <th scope="row">
                                        </th>
                                        <td>
                                            <div class="media-body">
                                                <div class="d-flex">
                                                    <h3>Số lượng sản phẩm: {{ request.session.cart_items }}</h3>
                                                </div>
                                                <div class="media-body">
                                                </div>
                                            </div>
                                        </td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td style="width:176px">
                                            <div class="media-body">
                                                <div class="d-flex">
                                                    {% include 'pages/xoatatcasanpham.html' %}
                                                </div>
                                            </div>
                                        </td>
                                    </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart_totals_area">
                        <h4>Thông tin giỏ hàng</h4>
                        <div class="cart_t_list">
                            <div class="media">
                                <div class="d-flex">
                                    <h5>Phí vận chuyển</h5>
                                </div>
                                <div class="media-body">
                                    <h6>30000 VNĐ</h6>
                                </div>
                            </div>
                            <div class="media">
                                <div class="d-flex">
                                    <h5>Giao hàng</h5>
                                </div>
                                <div class="media-body">
                                    <p>Vận chuyển toàn quốc</p>
                                </div>
                            </div>
                        </div>
                        <div class="total_amount row m0 row_disable">
                            <div class="float-left">
                                Tổng tiền
                            </div>
                            <div class="float-right">
                                {{GioHangs.TongTien}} VNĐ
                            </div>
                        </div>
                    </div>
                    <a role="button" href="{% url 'giohang:checkout' %}" class="btn subs_btn form-control">Đặt hàng</a>
                </div>
            </div>
        </div>
    </section>
{% endblock  %}

{% block jsblock %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'home/js/jquery-3.2.1.min.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'home/js/popper.min.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <!-- Rev slider js -->
    <script src="{% static 'home/vendors/revolution/js/jquery.themepunch.tools.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/jquery.themepunch.revolution.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.actions.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.video.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.navigation.min.js' %}"></script>
    <script src="{% static 'home/vendors/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"></script>
    <!-- Extra plugin css -->
    <script src="{% static 'home/vendors/counterup/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'home/vendors/counterup/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'home/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'home/vendors/bootstrap-selector/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'home/vendors/image-dropdown/jquery.dd.min.js' %}"></script>
    <script src="{% static 'home/js/smoothscroll.js' %}"></script>
    <script src="{% static 'home/vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'home/vendors/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'home/vendors/magnify-popup/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'home/vendors/vertical-slider/js/jQuery.verticalCarousel.js' %}"></script>
    <script src="{% static 'home/vendors/jquery-ui/jquery-ui.js' %}"></script>
    <script src="{% static 'home/js/theme.js' %}"></script>
{% endblock %}

PythonWeb/giohang/templates/pages/danhmuc.html
{% for loaisanpham in LoaiSanPhams %}
        <li class="nav-item">
            <a alt="{{loaisanpham.TenLSP}}" href="{% url 'sanphamtheoloai' loaisanpham.id %}"  class="nav-link">
                {{loaisanpham.TenLSP}}
            </a>
        </li>
{% endfor %}

PythonWeb/giohang/templates/pages/navbar.html
<!--{% load static %}-->
<!--<style>-->
<!--    .cart_cart a:before {-->
<!--        content: "{{ request.session.cart_items }}";-->
<!--    }-->
<!--</style>-->

<!--<header class="shop_header_area carousel_menu_area">-->
<!--    <div class="carousel_top_header black_top_header row m0">-->
<!--        <div class="container">-->
<!--            <div class="carousel_top_h_inner">-->
<!--                <div class="float-md-right">-->
<!--                    <ul class="account_list">-->
<!--                        {% include 'pages/topmenu.html' %}-->
<!--                    </ul>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="carousel_menu_inner">-->
<!--        <div class="container">-->
<!--            <nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--                <a class="navbar-brand" href="/"><img src="{% static 'home/img/logo.png' %}" alt="" style="width:250px"></a>-->
<!--                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--                    <span class="navbar-toggler-icon"></span>-->
<!--                </button>-->
<!--                <div class="collapse navbar-collapse" id="navbarSupportedContent">-->
<!--                    <ul class="navbar-nav mr-auto">-->
<!--                        <li class="nav-item dropdown submenu active">-->
<!--                            <a class="nav-link dropdown-toggle" href="" role="button"  aria-haspopup="true" aria-expanded="false">-->
<!--                                Trang chủ-->
<!--                            </a>-->
<!--                        </li>-->
<!--                        <li class="nav-item dropdown submenu">-->
<!--                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--                                Danh mục <i class="fa fa-angle-down" aria-hidden="true"></i>-->
<!--                            </a>-->
<!--                            <ul class="dropdown-menu">-->
<!--                                {% include 'pages/danhmuc.html' %}-->
<!--                            </ul>-->
<!--                        </li>-->
<!--                        <li class="nav-item"><a class="nav-link" href="/">Tin tức</a></li>-->
<!--                        <li class="nav-item"><a class="nav-link" href="/">Liên hệ</a></li>-->
<!--                    </ul>-->
<!--                    <ul class="navbar-nav justify-content-end">-->
<!--                        &lt;!&ndash;<li class="search_icon"><a href="#"><i class="icon-magnifier icons"></i></a></li>&ndash;&gt;-->
<!--                        <li class="user_icon"><a href="{% url 'user:thongtintaikhoan'%}"><i class="icon-user icons"></i></a></li>-->
<!--                        <li class="cart_cart"><a href="{% url 'giohang:home' %}"><i class="icon-handbag icons"></i></a></li>-->
<!--                    </ul>-->
<!--                </div>-->
<!--            </nav>-->
<!--        </div>-->
<!--    </div>-->
<!--</header>-->

PythonWeb/giohang/templates/pages/topmenu.html
{% if user.username %}
    <li style="color: white;">Xin chào {{user.username}}</li>
    <li><a href="{% url 'user:dangxuat' %}">Đăng xuất</a></li>
{% else %}
    <li><a href="{% url 'user:dangky' %}">Đăng ký</a></li>
    <li><a href="{% url 'user:dangnhap' %}">Đăng nhập</a></li>
{% endif %}

PythonWeb/giohang/templates/pages/xoakhoigiohang.html
{% load static %}
<style>
    .add_cart_btn {
        background: none;
        border: none;
    }
</style>

<form method="post" action="{% url 'giohang:delete' %}" class="form">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{sanpham.id}}" />
    <button type="submit" class="add_cart_btn">
        <img src="{% static 'home/img/icon/close-icon.png' %}" alt="">
    </button>
</form>