PythonWeb/PythonWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    # Tạo đường dẫn liên kết với các app
    path('', include('sanpham.urls')),
    path('user/', include('user.urls')),
    path('gio-hang/', include('giohang.urls')),
    path('tim-kiem/', include('timkiem.urls')),
    path('phongthuy/', include('phongthuy.urls')),
    url(r'^admin/', include('dbbackup_ui.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PythonWeb/giohang/urls.py
from django.urls import path
from . import views

app_name = 'giohang'
urlpatterns = [
    path('', views.cart_home, name='home'),
    path('cap-nhat/', views.cart_update, name='update'),
    path('xoa/', views.cart_delete, name='delete'),
    path('xoa-tat-ca/', views.cart_deleteall, name='deleteall'),
    #path('updatesl/', views.cart_updatesl, name='updatesl'),
    path('gio-hang-trong/', views.cart_empty, name='giohangtrong'),
    path('thanh-toan/', views.checkout_home, name='checkout'),
    path('thanh-cong/', views.thanhcong, name='thanhcong'),
]

PythonWeb/news/urls.py
from django.urls import path
from . import views

app_name = 'tintuc'
urlpatterns = [
    path('', views.home, name='news'),
    path("<int:id>/", views.tintuc, name='tintuc'),
]

PythonWeb/sanpham/urls.py
from django.urls import path

from . import views

app_name = 'sanpham'
urlpatterns = [
    path('', views.index, name='simso'),
    path("san-pham/<str:slug>", views.sanpham, name='sanpham'),
    path('sim-theo-gia/<str:slug>', views.simtheogia, name='simtheogia'),
    path('sim-theo-mang/<str:slug>', views.simtheomang, name='simtheomang'),
    path('sim-theo-loai/<str:slug>', views.simtheoloai, name='simtheoloai'),
    path('sim-nam-sinh/<str:slug>', views.simnamsinh, name='simnamsinh'),


]

PythonWeb/user/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from sanpham import models
import operator


app_name = 'user'
urlpatterns = [
    path("dang-ky/", views.dangky, name='dangky'),
    path("dang-nhap/", auth_views.LoginView.as_view(template_name='simso/page-user/dangnhap.html',
                                                    extra_context={
                                                        "stl": models.SimTheoLoai.objects.all(),
                                                        "sns": models.SimNamSinh.objects.all(),
                                                        "nm": models.NhaMang.objects.all(),
                                                        # "stg": sorted(models.SimTheoGia.objects.all(), key=operator.attrgetter('title')),
                                                    }),
         name='dangnhap'),
    path("dang-xuat/", auth_views.LogoutView.as_view(next_page='/'), name='dangxuat'),
    path("thong-tin-tai-khoan/", views.thongtintaikhoan, name='thongtintaikhoan'),
    path("doi-mat-khau/", views.doimatkhau, name='doimatkhau'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path("xac-thuc/", views.verify, name='xacthuc'),
    path("xac-thuc-sdt/", views.checkcode, name='xacthucsdt'),

]

PythonWeb/sanpham/models.py
from django.db import models
from django.template.defaultfilters import truncatechars
from PythonWeb.utils import get_unique_slug

##
# Chọn sim vip _ thường
##

Default_img = '/default.png'


SIM_CHOICES = (
    ('khuyenmai', 'Khuyến Mãi'),
    ('thuong', 'Sim Thường'),
    ('vip', 'Sim Vip'),
    ('vipdn', 'Sim Vip Doanh Nhân'))

##
# Tạo danh muc san pham _Duc
##
class SimTheoGia(models.Model):
    title = models.CharField(max_length=100,verbose_name='Tiêu đề')
    slug = models.SlugField(max_length=20, null=False, default='')

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'title', 'slug')
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Sim theo giá'


class NhaMang(models.Model):
    title = models.CharField(max_length=100,verbose_name='Tiêu đề')
    slug = models.SlugField(max_length=20, null=False, default='')

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'title', 'slug')
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Nhà mạng'


class SimTheoLoai(models.Model):
    title = models.CharField(max_length=100,verbose_name='Tiêu đề')
    slug = models.SlugField(max_length=20, null=False, default='')

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'title', 'slug')
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Sim theo loại'


class SimNamSinh(models.Model):
    title = models.CharField(max_length=100,verbose_name='Tiêu đề')
    slug = models.SlugField(max_length=20, null=False, default='')

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'title', 'slug')
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Sim năm sinh'


# Tạo bảng sản phẩm

class SanPham(models.Model):
    LoaiSims = models.ManyToManyField(SimTheoLoai,default=0, verbose_name='Loại sim')
    slug = models.SlugField(max_length=20, null=False, default='')
    TacVu = models.CharField(max_length=100, choices=SIM_CHOICES,default='thuong',verbose_name='Tác vụ trang chủ')
    SoSim = models.CharField(max_length=100, verbose_name='Nhập số sim')
    Gia = models.IntegerField(default=0, verbose_name='Nhập giá bán')
    Mang = models.ForeignKey(NhaMang, on_delete=models.CASCADE, null=True, verbose_name='Nhà Mạng')
    LoaiGia = models.ForeignKey(SimTheoGia, on_delete=models.CASCADE, null=True, verbose_name='Sim theo giá ')
    NamSinh = models.ForeignKey(SimNamSinh, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Theo năm sinh ')
    Anh = models.ImageField(default=Default_img, verbose_name='Hình đại diện')
    NgayNhap = models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập')

    def __str__(self):
        return self.SoSim

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'SoSim', 'slug')
        super().save(*args, **kwargs)

    # def get_loaisims(self):
    #     return " - ".join([s.title for s in self.LoaiSims.all()])

    class Meta:
        verbose_name_plural = 'Sản Phẩm'

PythonWeb/sanpham/views.py
from django.db.models import Max
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import ListView

from .models import SanPham, SimTheoLoai, SimNamSinh, NhaMang, SimTheoGia
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from giohang.models import GioHang, CTGH
from user.models import CustomerUser
from news.models import TinTuc
import operator

# Create your views here.
def index(request):
    # Lấy dữ liệu từ database
    km = SanPham.objects.filter(TacVu='khuyenmai')
    vip = SanPham.objects.filter(TacVu='vip')
    vipdn = SanPham.objects.filter(TacVu='vipdn')
    thuong = SanPham.objects.filter(TacVu='thuong')

    stl = SimTheoLoai.objects.all()
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()

    # Sắp xếp danh mục sim theo giá theo title
    stg_dsx = sorted(stg, key=operator.attrgetter('title'))

    Data = {
            "km": km,
            "vip": vip,
            "vipdn": vipdn,
            "thuong": thuong,
            "stl": stl,
            "sns": sns,
            "nm": nm,
            "stg": stg_dsx,
            }
    return render(request, "simso/index.html", Data)

def sanpham(request, slug):
    # Lấy dữ liệu từ database
    sanpham = SanPham.objects.get(slug=slug)

    stl = SimTheoLoai.objects.all()
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()

    #Sắp xếp danh mục sim theo giá theo title
    stg_dsx = sorted(stg, key=operator.attrgetter('title'))

    Data = {'sanpham': sanpham,
            "stl": stl,
            "sns": sns,
            "nm": nm,
            "stg": stg_dsx,
            }
    return render(request, 'simso/detail-sim/detail-sim.html', Data)

def error(request):
    return render(request, 'simso/page-user/error.html')


def simtheogia(request, slug):

    stg1 = SimTheoGia.objects.get(slug=slug)
    sanpham = stg1.sanpham_set.all()

    paginator = Paginator(sanpham, 10)  # Show 25 contacts per page

    page = request.GET.get('page')
    sanphams = paginator.get_page(page)

    stl = SimTheoLoai.objects.order_by('?')
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()

    # Sắp xếp danh mục sim theo giá theo title
    stg_dsx = sorted(stg, key=operator.attrgetter('title'))

    Data = {
            'stg1': stg1,
            'sanpham': sanphams,
            "stl": stl,
            "sns": sns,
            "nm": nm,
            "stg": stg_dsx,
            }
    return render(request, 'simso/category/sim-theo-gia.html', Data)


def simtheomang(request, slug):

    nm1 = NhaMang.objects.get(slug=slug)
    sanpham = nm1.sanpham_set.all()

    paginator = Paginator(sanpham, 10)  # Show 25 contacts per page

    page = request.GET.get('page')
    sanphams = paginator.get_page(page)

    stl = SimTheoLoai.objects.order_by('?')
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()

    # Sắp xếp danh mục sim theo giá theo title
    stg_dsx = sorted(stg, key=operator.attrgetter('title'))

    Data = {
            'nm1': nm1,
            'sanpham': sanphams,
            "stl": stl,
            "sns": sns,
            "nm": nm,
            "stg": stg_dsx,
            }
    return render(request, 'category/sim-theo-mang.html', Data)

def simtheoloai(request, slug):

    stl1 = SimTheoLoai.objects.get(slug=slug)
    sanpham = stl1.sanpham_set.all()

    paginator = Paginator(sanpham, 10)  # Show 25 contacts per page

    page = request.GET.get('page')
    sanphams = paginator.get_page(page)

    stl = SimTheoLoai.objects.order_by('?')
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()

    # Sắp xếp danh mục sim theo giá theo title
    stg_dsx = sorted(stg, key=operator.attrgetter('title'))

    Data = {
            'stl1': stl1,
            'sanpham': sanphams,
            "stl": stl,
            "sns": sns,
            "nm": nm,
            "stg": stg_dsx,
            }
    return render(request, 'category/sim-theo-loai.html', Data)


def simnamsinh(request, slug):

    sns1 = SimNamSinh.objects.get(slug=slug)
    sanpham = sns1.sanpham_set.all()

    paginator = Paginator(sanpham, 10)  # Show 25 contacts per page

    page = request.GET.get('page')
    sanphams = paginator.get_page(page)

    stl = SimTheoLoai.objects.order_by('?')
    sns = SimNamSinh.objects.all()
    nm = NhaMang.objects.all()
    stg = SimTheoGia.objects.all()

    # Sắp xếp danh mục sim theo giá theo title
    stg_dsx = sorted(stg, key=operator.attrgetter('title'))

    Data = {
            'sns1': sns1,
            'sanpham': sanphams,
            "stl": stl,
            "sns": sns,
            "nm": nm,
            "stg": stg_dsx,
            }
    return render(request, 'simso/category/sim-nam-sinh.html', Data)


def tknc(request, slug):
    sp = SanPham.objects.get(slug=slug)
    Data = {
            'sp':sp,
            }
    return render(request, 'includes/timkiem/timkiem-nangcao.html', Data)

PythonWeb/sanpham/templates/simso/page-cart/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Giỏ hàng
{% endblock %}

{% static "" as baseUrl %}
{% load humanize %}

{% block index %}
<article>
    <section class="shopping_cart_area p_100">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="cart_items">
                        <h1>Giỏ hàng của bạn</h1>
                        <div class="table-responsive-md">
                            <table class="table">
                                <tbody>
                                        <tr>
                                            <th scope="row"></th>
                                            <td><strong><font size="3">Ảnh</font></strong></td>
                                            <td><strong><font size="3">Sim</font></strong></td>
                                            <td><strong><font size="3">Giá</font></strong></td>
                                        </tr>
                                    {% for sanpham in GioHangs.SanPhams.all %}
                                        <tr>
                                            <th scope="row">
                                                {% include 'simso/page-cart/xoakhoigiohang.html' %}
                                            </th>
                                            <td>
                                                <a href="{% url 'sanpham:sanpham' sanpham.slug %}">
                                                    <img src="{{sanpham.Anh.url}}" alt="{{sanpham.TenSanPham}}" style="width: 200px; height: 123px;" />
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{% url 'sanpham:sanpham' sanpham.slug %}" style="text-decoration: none;color: black;">
                                                    <span ><strong><font size="3">{{sanpham.SoSim}}</font></strong></span>
                                                </a>
                                            </td>
                                            <td><p class="red"><strong><font size="3">{{ sanpham.Gia|intcomma }}₫</font></strong></p></td>
                                        </tr>
                                    {% endfor %}
                                    <tr class="last">
                                        <th scope="row">
                                            {% include 'simso/page-cart/xoatatcasanpham.html' %}
                                        </th>
                                        <td>
                                            <div class="media-body">
                                                <div class="d-flex">
                                                    <h3>Số lượng sim: {{ request.session.cart_items }}</h3>
                                                </div>
                                            </div>
                                        </td>
                                        <td >
                                            <div class="media-body">
                                                <div class="d-flex">
                                                    <h3>Tổng tiền</h3>

                                                </div>
                                            </div>
                                        </td>
                                        <td >
                                            <div class="media-body">
                                                <div class="d-flex">
                                                    <strong><font size="3">{{GioHangs.TongTien|intcomma }}₫</font></strong>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <div style="text-align:center; margin-top:10px;">
                                <a role="button" href="{% url 'giohang:checkout' %}" class="btn btn-primary " style="color:white; text-decoration: none;">Đặt hàng</a>
                            </div>


                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart_totals_area">
                        <br>
                        <div style=" background: #fff; border: 1px solid #ccc; ">
                            <div style=" padding:10px; ">
                                <strong>Hướng dẫn cách thức mua sim 0962.333.529:</strong><br>


                                    ▪ Cách 1: Sim Thăng Long giao sim và thu tiền tận nhà miễn phí (áp dụng Hà Nội, Tp.HCM và các tỉnh/thành có đại lý)<br>
                                    ▪ Cách 2: Quý khách đến cửa hàng tại Hà Nội hoặc Tp.HCM (<a href="/sim-so-dep/10/lien-he.html">Xem địa chỉ cửa hàng tại đây</a>)<br>
                                    ▪ Cách 3: Đặt cọc và thanh toán tiền còn lại khi nhận sim (áp dụng tại các tỉnh không có đại lý):
                                    Quý khách đảm bảo việc mua hàng bằng cách đặt cọc tối thiểu 10% giá trị sim qua chuyển khoản hoặc mã thẻ cào (<a href="/bai-viet/65/cach-mua-sim-va-thanh-toan.html">Xem danh sách tài khoản ngân hàng tại đây</a>). Chúng tôi sẽ gửi bưu điện phát sim đến tay quý khách và thu tiền còn lại <em>(Hệ thống bưu điện trên cả nước đều cung cấp dịch vụ thu hộ tiền cho người bán - gọi tắt là COD. Theo đó, bưu điện sẽ giao hàng (sim) đến tận tay quý khách và thu tiền cho chúng tôi)</em>

                                <br>
                                <br>
                                <em>Chúc quý khách gặp nhiều may mắn khi sở hữu thuê bao <strong>0962.333.529</strong></em>
                            </div>
                        </div>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </section>
</article>
<style>
    .table {
        border-collapse: collapse;
        width: 100%;
    }
    .table, .table th, .table td {
        text-align: center;
        border: 1px solid black;
    }
    th {
        padding: 2px;
        height: 50%;
    }
    td {
        padding: 2px;
    }
</style>
{% endblock  %}

PythonWeb/sanpham/templates/simso/page-cart/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}
Đặt hàng
{% endblock %}

{% block index %}
   <article>
        <section class="register_area p_100">
            <div class="container">
                <div class="register_inner">
                    <div>
                            <h5 style="color:red;">{{Error}}</h5>
                    </div>
                    <div class="row">
                        <div class="col-lg-7">
                            <div class="billing_details" style="text-align:center">
                                <h1 class="reg_title">Thông tin đặt hàng</h1>
                                <hr/>
                                <div class="billing_inner row" style="width:90%;text-align:left">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="name"><strong>Họ tên</strong><span style="color:red">*</span></label>
                                            <input type="text" class="form-control" id="name" aria-describedby="name" name="HoTen" value="{{user.HoTen}}" readonly />
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="address"><strong>Địa chỉ</strong><span style="color:red">*</span></label>
                                            <input type="text" class="form-control" id="address" aria-describedby="address" name="DiaChi" value="{{user.DiaChi}}" readonly />
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="email"><strong>Email</strong><span style="color:red">*</span></label>
                                            <input type="email" class="form-control" id="email" aria-describedby="email" name="Email" value="{{user.email}}" readonly />
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label for="phone1"><strong>Số điện thoại</strong><span style="color:red">*</span></label>
                                            <input type="text" class="form-control" id="phone1" aria-describedby="phone" name="SoDienThoai" value="{{user.SDT}}" readonly />
                                        </div>
                                    </div>
                                    <div style="width: 110%">
                                        <div class="form-group" style="text-align:center">
                                            <a id="cstt" href="{% url 'user:thongtintaikhoan'%}" role="button" class="btn btn-primary" style="color:white; text-decoration: none;">Chỉnh sửa thông tin</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr />
                        <div class="col-lg-5">
                            <div class="order_box_price" style="text-align:center">
                                <h1 class="reg_title">Đơn đặt hàng của bạn</h1>
                                <div class="payment_list">
                                    <div class="price_single_cost">
                                        <table class="table">
                                            <tbody>
                                                <tr>
                                                    <td><strong>Sim</strong></td>
                                                    <td><strong>Giá</strong></td>
                                                </tr>
                                                {% for item in CTGHs %}
                                                    <tr>
                                                        <td>
                                                            <h5><strong><font size="3">{{item.SP}}</font></strong></h5>
                                                        </td>
                                                        <td>
                                                            <span><strong><font size="3">{{item.DonGia|intcomma }}₫</font></strong></span>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                                <tr>
                                                    <td><strong><font size="3">Giao hàng</font></strong></td>
                                                    <td><strong><font size="3">Miễn phí</font></strong></td>
                                                </tr>
                                                <tr>
                                                    <td><strong><font size="3">Tổng tiền</font></strong></td>
                                                    <td><strong><font size="3">{{Cart_obj.TongTien|intcomma }}₫</font></strong></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <br/>
                                    <div id="accordion" role="tablist" class="price_method" style="display:flex">
                                        <div class="card" style="margin:10px 0px 0px 50px">
                                            <div id="collapseOne" class="collapse show" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
                                                <div class="card-body">
                                                    <form class="billing_inner row" method="post" action="">
                                                        {% csrf_token %}
                                                        <button type="submit" value="submit" class="btn btn-success" style="margin-left: 15px;">Thanh toán khi nhận hàng</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="card" style="margin-left: 50px">
                                            <div id="collapseTwo" class="collapse show" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
                                                <div class="card-body">
                                                    {% include 'pages/paypal.html' %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
   </article>
<style>
    .table {
        border-collapse: collapse;
        width: 100%;
    }
    .table, .table th, .table td {
        text-align: center;
        border: 1px solid black;
    }
    th {
        padding: 2px;
        height: 50%;
    }
    td {
        padding: 2px;
    }
</style>
{% endblock  %}

PythonWeb/sanpham/templates/simso/page-cart/giohangtrong.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Giỏ hàng trống
{% endblock %}

{% block index %}
<article>
    <section class="emty_cart_area p_100">
        <div class="container">
            <div class="emty_cart_inner" style="text-align:center">
                <i class="icon-handbag icons"></i>
                <h1>Giỏ hàng của bạn trống</h1>
                <h2>Quay lại <a href="/">trang chủ</a></h2>
            </div>
        </div>
    </section>
</article>
{% endblock  %}

PythonWeb/sanpham/templates/simso/page-cart/paypal.html
<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
    <input type="hidden" name="cmd" value="_cart" />
    <input type="hidden" name="upload" value="1" />
    <input type="hidden" name="business" value="ntxl1210-facilitator@gmail.com" />
    <input type="hidden" name="return" value="http://{{request.get_host}}{% url 'giohang:thanhcong' %}" />
    <input type="hidden" name="cancel" value="http://{{request.get_host}}{% url 'giohang:checkout' %}" />
    <input type="hidden" name="currency_code" value="USD" />

    {% for item in CTGHs %}
        <input type="hidden" name="item_number_{{forloop.counter}}" value="{{item.id}}" />
        <input type="hidden" name="item_name_{{forloop.counter}}" value="{{item.SP}}" />
        <input type="hidden" name="quantity_{{forloop.counter}}" value="1" />
        <input type="hidden" name="amount_{{forloop.counter}}" value="{{item.ToUSD}}" />
    {% endfor %}
    <input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"/>
</form>

PythonWeb/sanpham/templates/simso/page-cart/thanhcong.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Đặt hàng thành công
{% endblock %}

{% block index %}
<article>
    <section class="emty_cart_area p_100">
        <div class="container">
            <div class="emty_cart_inner" style="text-align:center">
                <i class="icon-handbag icons"></i>
                <h1>Bạn đã đặt hàng thành công. Chúng tôi sẽ liên hệ với bạn để xác nhận và giao hàng đúng hẹn.</h1>
                <h2>Quay lại <a href="/">trang chủ</a></h2>
            </div>
        </div>
    </section>
</article>
{% endblock  %}

PythonWeb/sanpham/templates/simso/page-cart/thongtinhoadon.html
{% load humanize %}
{% autoescape off %}
    <p>Xin chào {{ user.username }},</p>
    <p>Thông tin đơn hóa đơn của bạn:</p>
    <table class="table" style="text-align: center;">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Số sim</th>
                <th scope="col">Giá</th>
            </tr>
        </thead>
        <tbody>
            {% for item in Ctghs %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{item.SP}}</td>
                    <td>{{item.DonGia|intcomma }}₫</td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="2"></td>
                <td>Phí vận chuyển: Miễn phí</td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td>Tổng tiền: {{Cart_obj.TongTien|intcomma }}₫</td>
            </tr>
        </tbody>
    </table>
    <p>Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi, nếu có thắc mắc hãy liên lạc với chúng tôi để được giải đáp.</p>
    <p>Hotline: xxxxxxxxx || Email: ntxl1210@gmail.com</p>
{% endautoescape %}

PythonWeb/sanpham/templates/simso/page-cart/xoakhoigiohang.html
{% load static %}
<style>
    .add_cart_btn {
        background: none;
        border: none;
    }
</style>

<form method="post" action="{% url 'giohang:delete' %}" class="form">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{sanpham.id}}" />
    <button type="submit" class="add_cart_btn">
        <i class="fa fa-close fa-2x"></i>
    </button>
</form>

PythonWeb/sanpham/templates/simso/page-cart/xoatatcasanpham.html
{% load static %}
<style>
    button{
        clear: both;
        background: None;
        color: black;
        border: None;
    }
    button a p{
        text-decoration: underline;
    }
</style>

<form method="post" action="{% url 'giohang:deleteall' %}" class="form">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{sanpham.id}}" />
    <button type="submit">
        <i class="fa fa-trash fa-2x"></i>
    </button>
</form>